"""Token administration.

`api_tokens` exists but until now nothing outside the tests could write to it,
which meant the per-principal authorization model was unreachable in a real
deployment: an operator had no way to issue the credential the design assumed.

These endpoints close that gap. They are deliberately restricted to the shared
admin token, so issuing a scoped credential always requires the full-privilege
one. A scoped principal cannot mint another principal, which would make the
scope system advisory rather than enforced.

The plaintext token is returned exactly once, at creation. It is stored as a
SHA-256 digest and cannot be recovered afterwards, so a lost token means issuing
a new one rather than reading the old one back. That is a deliberate
inconvenience: the alternative is a stored plaintext credential in the database.
"""

from __future__ import annotations

import secrets
import time

from fastapi import APIRouter, Header, HTTPException, Request

from .config import settings
from .db import transaction
from .ratelimit import check_rate
from .security import (
    create_token,
    delete_token,
    list_tokens,
    require_bearer_token,
)

router = APIRouter(prefix="/v1", tags=["tokens"])

SCOPES = ("read", "write", "admin")
MAX_TOKEN_LENGTH = 128


def _require_admin(authorization: str | None) -> None:
    # The shared admin token only. A scoped principal must not be able to widen
    # its own reach by issuing itself a broader credential.
    require_bearer_token(authorization, settings.api_token, "admin")


def _validate_scopes(scopes: str) -> list[str]:
    requested = [s.strip() for s in scopes.split(",") if s.strip()]
    if not requested:
        raise HTTPException(status_code=422, detail="missing_scopes")
    unknown = [s for s in requested if s not in SCOPES]
    if unknown:
        raise HTTPException(
            status_code=422,
            detail={"error": "invalid_scopes", "allowed": list(SCOPES),
                    "unknown": unknown},
        )
    # 'admin' subsumes the rest; storing all three would imply more than is
    # meant and would make a revoked scope look still present.
    if "admin" in requested:
        return ["admin"]
    return requested


def _validate_site_id(site_id: str | None) -> str | None:
    if site_id is None:
        return None
    if not isinstance(site_id, str) or not site_id:
        raise HTTPException(status_code=422, detail="invalid_site_id")
    # Reuse the identifier rule so a scoped credential cannot be minted for a
    # site id that no site could ever have.
    from .evaluation import _require_site_id

    _require_site_id(site_id)
    return site_id


@router.post("/tokens")
def issue_token(
    payload: dict,
    request: Request,
    authorization: str | None = Header(default=None),
) -> dict:
    check_rate(request)
    _require_admin(authorization)

    name = payload.get("name")
    if not isinstance(name, str) or not name or len(name) > 64:
        raise HTTPException(status_code=422, detail="invalid_name")

    # A caller may supply the secret, which matters when credentials are
    # generated by an external system. Otherwise one is made here.
    token = payload.get("token")
    if token is None:
        token = secrets.token_urlsafe(32)
    elif not isinstance(token, str) or not token or len(token) > MAX_TOKEN_LENGTH:
        raise HTTPException(status_code=422, detail="invalid_token")

    # An explicitly empty scope list is a mistake worth reporting, not a
    # silent upgrade to `read`: `""` is falsy, so `payload.get(...) or "read"`
    # would hand back a working credential nobody asked for.
    if "scopes" in payload and payload["scopes"] is None:
        raise HTTPException(status_code=422, detail="missing_scopes")
    raw_scopes = payload.get("scopes", "read")
    if not isinstance(raw_scopes, str):
        raise HTTPException(status_code=422, detail="invalid_scopes")
    scopes = _validate_scopes(raw_scopes)
    site_id = _validate_site_id(payload.get("site_id"))

    created_at = int(time.time() * 1000)
    if not create_token(name, token, ",".join(scopes), site_id, created_at):
        raise HTTPException(status_code=409, detail="token_name_exists")

    return {
        "status": "issued",
        "name": name,
        "scopes": scopes,
        "site_id": site_id,
        "created_at_utc_ms": created_at,
        # Shown once and never again: only the digest is kept.
        "token": token,
        "note": (
            "store this now; the central keeps only a SHA-256 digest and "
            "cannot show it again"
        ),
    }


@router.get("/tokens")
def show_tokens(
    request: Request,
    authorization: str | None = Header(default=None),
) -> dict:
    check_rate(request)
    _require_admin(authorization)
    return {
        "tokens": list_tokens(),
        "note": (
            "digests are never returned; a lost token is replaced, not "
            "recovered"
        ),
    }


@router.delete("/tokens/{name}")
def revoke_token(
    name: str,
    request: Request,
    authorization: str | None = Header(default=None),
) -> dict:
    check_rate(request)
    _require_admin(authorization)
    if not delete_token(name):
        raise HTTPException(status_code=404, detail="token_not_found")
    return {"status": "revoked", "name": name}


@router.get("/tokens/{name}")
def describe_token(
    name: str,
    request: Request,
    authorization: str | None = Header(default=None),
) -> dict:
    check_rate(request)
    _require_admin(authorization)
    for row in list_tokens():
        if row["name"] == name:
            return row
    raise HTTPException(status_code=404, detail="token_not_found")


def ensure_defaults() -> None:
    """Creates the api_tokens table on an existing database.

    The schema runs on every boot, so this only matters for databases created
    before the table existed; kept explicit because a missing table would
    otherwise surface as a 500 on the first token request rather than as a
    clear signal at startup.
    """
    with transaction() as conn:
        conn.execute(
            """CREATE TABLE IF NOT EXISTS api_tokens (
                   name TEXT PRIMARY KEY,
                   token_sha256 TEXT NOT NULL UNIQUE,
                   scopes TEXT NOT NULL DEFAULT 'read',
                   site_id TEXT,
                   created_at_utc_ms INTEGER NOT NULL DEFAULT 0)"""
        )
