// Pinned to the bytes the backend actually emits.
//
// The literal below is the output of Python's `json.dumps` on the challenge dict, copied
// verbatim including its spaces after the colons. It is a literal rather than a read from a
// fixture file on purpose: a fixture generated by running the backend would let the test pass
// against whatever the backend emits today, which is the test passing by construction rather
// than by agreement. `test_the_serialised_form_is_still_what_dumps_produces` in the backend is
// what keeps the two sides in step.
//
// This file exists because the parser's refusal of JSON escapes was wrong in a way no
// hand-written fixture would have caught: those fixtures were written to match the parser, and
// so agreed with it perfectly while disagreeing with the server.
#include <cstring>
#include <unity.h>

#include "cauce/app/NodeAuthenticator.h"

namespace cauce::app {

// Spaces after the colons are `json.dumps` defaults and are part of the contract.
const char kSerialisedChallenge[] =
    "{\"node_id\": \"CAUCE-001\", \"nonce\": \"NOnCE\", "
    "\"expires_utc_ms\": 1787356860000, "
    "\"sign_this\": \"cauce-sync-challenge\\nCAUCE-001\\nNOnCE\\n1787356860000\"}";

void test_the_serialised_challenge_reads_field_by_field() {
  char signThis[256];
  TEST_ASSERT_TRUE(NodeAuthenticator::jsonStringField(
      kSerialisedChallenge, "sign_this", signThis, sizeof(signThis)));
  TEST_ASSERT_EQUAL_STRING(
      "cauce-sync-challenge\nCAUCE-001\nNOnCE\n1787356860000", signThis);

  char nodeId[16];
  TEST_ASSERT_TRUE(NodeAuthenticator::jsonStringField(
      kSerialisedChallenge, "node_id", nodeId, sizeof(nodeId)));
  TEST_ASSERT_EQUAL_STRING("CAUCE-001", nodeId);

  char nonce[64];
  TEST_ASSERT_TRUE(NodeAuthenticator::jsonStringField(
      kSerialisedChallenge, "nonce", nonce, sizeof(nonce)));
  TEST_ASSERT_EQUAL_STRING("NOnCE", nonce);

  uint64_t expiry = 0;
  TEST_ASSERT_TRUE(
      NodeAuthenticator::jsonUintField(kSerialisedChallenge, "expires_utc_ms", expiry));
  TEST_ASSERT_EQUAL_UINT64(1787356860000ULL, expiry);
}

// The three escapes the canonical string relies on are the only reason this module has to
// decode anything. If a value carries a quote instead, `\"` must also round-trip, because a
// nonce is server-issued and a central that generated a quote in one would otherwise leave a
// node unable to authenticate at all.
void test_a_quoted_character_in_a_value_round_trips() {
  const char* json = "{\"nonce\": \"NOn\\\"CE\"}";
  char nonce[64];
  TEST_ASSERT_TRUE(
      NodeAuthenticator::jsonStringField(json, "nonce", nonce, sizeof(nonce)));
  TEST_ASSERT_EQUAL_STRING("NOn\"CE", nonce);
}

}  // namespace

void registerNodeAuthWireTests() {
  UNITY_BEGIN();
  RUN_TEST(cauce::app::test_the_serialised_challenge_reads_field_by_field);
  RUN_TEST(cauce::app::test_a_quoted_character_in_a_value_round_trips);
}