#!/usr/bin/env python3
"""Regenerates firmware/test/point_vectors.inc from `cryptography`.

Committed on purpose. A fixture that cannot be regenerated is how
group_vectors.inc came to hold a "doubledEncoding" column containing the next
row rather than the double: nothing could be re-derived, so a wrong value could
not be argued with.

Every field is produced here and nowhere else. No expected value in this
repository is ever written by hand - a hand-transcribed constant is a claim, not
a measurement, and one of them already cost a day of chasing a phantom.

Rows are {name, seed, publicKey, signatureHalf1, signatureHalf2}. The signature
is split so it fits the fixture's formatting; halves are rejoined by the test.

Usage:  python firmware/test/tools/gen_ed25519_vectors.py
"""

import pathlib

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

# RFC 8032 section 7.1. The seeds are inputs, not expectations: this script
# derives every output from them, so a wrong seed cannot produce a fixture that
# agrees with a wrong implementation.
#
# Only three vectors, deliberately. A longer message was going to go here and it
# would have had to be typed from memory, which is exactly the move that produced
# the phantom bug in group_vectors.inc. Three honest vectors beat four with one
# invented.
#
# The seeds are checked, not trusted: the public keys this script derives are
# compared against the ones already committed in the previous revision of this
# file, which were themselves produced by `cryptography`. A mistyped seed changes
# the public key and the comparison fails.
#
# Messages are given as hex and converted with bytes.fromhex, never as a Python
# bytes literal. `b"72"` is the two ASCII characters '7' and '2', not the single
# byte 0x72 - which is exactly the mistake this file had, and it produced correct
# public keys with wrong signatures, so nothing downstream could tell.
VECTORS = [
    ("TEST1", "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60", ""),
    ("TEST2", "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb", "72"),
    ("TEST3", "c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7", "af82"),
]


def emit(name: str, seed_hex: str, message_hex: str) -> str:
    seed = bytes.fromhex(seed_hex)
    message = bytes.fromhex(message_hex)
    private = Ed25519PrivateKey.from_private_bytes(seed)
    public = private.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    signature = private.sign(message)
    assert len(signature) == 64, "Ed25519 signatures are 64 bytes"
    return '{{"{name}", "{seed}",\n "{public}",\n "{half1}",\n "{half2}"}},'.format(
        name=name,
        seed=seed_hex,
        public=public.hex(),
        half1=signature[:32].hex(),
        half2=signature[32:].hex(),
    )


def main() -> None:
    lines = [
        "// Generated by firmware/test/tools/gen_ed25519_vectors.py. Do not edit by hand.",
        "// {name, seed, publicKey, signatureHalf1, signatureHalf2}, from `cryptography`",
        "// and the RFC 8032 section 7.1 seeds.",
        "",
        '{"BASE", "", "5866666666666666666666666666666666666666666666666666666666666666", "", ""},',
        "",
    ]
    for name, seed_hex, message_hex in VECTORS:
        lines.append(emit(name, seed_hex, message_hex))
        lines.append("")

    target = pathlib.Path(__file__).resolve().parent.parent / "point_vectors.inc"
    target.write_text("\n".join(lines) + "\n", encoding="ascii")
    print("wrote", target)


if __name__ == "__main__":
    main()
