[platformio]
default_envs = native

[env]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions.csv
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -D CAUCE_NODE_ID_DEFAULT=\"CAUCE-001\"
build_src_filter = +<main.cpp>
lib_deps =
    bblanchon/ArduinoJson@^7.0.4

[env:native]
platform = native
build_flags =
    -std=c++17
    -Wall
    -Wextra
    -Wno-unused-parameter
    -D CAUCE_HOST_SIMULATION=1
build_src_filter = +<main.cpp>
test_build_src = false

[env:integration]
platform = native
build_flags =
    -std=c++17
    -Wall
    -Wextra
    -Wno-unused-parameter
    -D CAUCE_HOST_SIMULATION=1
    -lws2_32
build_src_filter = -<main.cpp> +<integration_main.cpp>
